//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 01:48:04 PM CEST 
//


package de.tum.in.i22.uc.pdp.xsd;

import ae.javax.xml.bind.annotation.XmlEnum;
import ae.javax.xml.bind.annotation.XmlEnumValue;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComparisonOperatorTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ComparisonOperatorTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="equals"/>
 *     &lt;enumeration value="dataInContainer"/>
 *     &lt;enumeration value="gt"/>
 *     &lt;enumeration value="ge"/>
 *     &lt;enumeration value="lt"/>
 *     &lt;enumeration value="le"/>
 *     &lt;enumeration value="notEquals"/>
 *     &lt;enumeration value="elementInList"/>
 *     &lt;enumeration value="listInList"/>
 *     &lt;enumeration value="startsWith"/>
 *     &lt;enumeration value="endsWith"/>
 *     &lt;enumeration value="substring"/>
 *     &lt;enumeration value="equalsIgnoreCase"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ComparisonOperatorTypes")
@XmlEnum
public enum ComparisonOperatorTypes {

    @XmlEnumValue("equals")
    EQUALS("equals"),
    @XmlEnumValue("dataInContainer")
    DATA_IN_CONTAINER("dataInContainer"),
    @XmlEnumValue("gt")
    GT("gt"),
    @XmlEnumValue("ge")
    GE("ge"),
    @XmlEnumValue("lt")
    LT("lt"),
    @XmlEnumValue("le")
    LE("le"),
    @XmlEnumValue("notEquals")
    NOT_EQUALS("notEquals"),
    @XmlEnumValue("elementInList")
    ELEMENT_IN_LIST("elementInList"),
    @XmlEnumValue("listInList")
    LIST_IN_LIST("listInList"),
    @XmlEnumValue("startsWith")
    STARTS_WITH("startsWith"),
    @XmlEnumValue("endsWith")
    ENDS_WITH("endsWith"),
    @XmlEnumValue("substring")
    SUBSTRING("substring"),
    @XmlEnumValue("equalsIgnoreCase")
    EQUALS_IGNORE_CASE("equalsIgnoreCase");
    private final String value;

    ComparisonOperatorTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ComparisonOperatorTypes fromValue(String v) {
        for (ComparisonOperatorTypes c: ComparisonOperatorTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
