//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 01:48:04 PM CEST 
//


package de.tum.in.i22.uc.pdp.xsd;

import java.util.ArrayList;
import java.util.List;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreventiveMechanismType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreventiveMechanismType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www22.in.tum.de/enforcementLanguage}MechanismBaseType">
 *       &lt;sequence>
 *         &lt;element name="authorizationAction" type="{http://www22.in.tum.de/enforcementLanguage}AuthorizationActionType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreventiveMechanismType", propOrder = {
    "authorizationAction"
})
public class PreventiveMechanismType
    extends MechanismBaseType
{

    @XmlElement(required = true)
    protected List<AuthorizationActionType> authorizationAction;

    /**
     * Gets the value of the authorizationAction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorizationAction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorizationAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthorizationActionType }
     * 
     * 
     */
    public List<AuthorizationActionType> getAuthorizationAction() {
        if (authorizationAction == null) {
            authorizationAction = new ArrayList<AuthorizationActionType>();
        }
        return this.authorizationAction;
    }

    public boolean isSetAuthorizationAction() {
        return ((this.authorizationAction!= null)&&(!this.authorizationAction.isEmpty()));
    }

    public void unsetAuthorizationAction() {
        this.authorizationAction = null;
    }

}
