//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 01:48:04 PM CEST 
//


package de.tum.in.i22.uc.pdp.xsd;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlAttribute;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlElements;
import ae.javax.xml.bind.annotation.XmlType;
import de.tum.in.i22.uc.pdp.core.condition.Operator;
import de.tum.in.i22.uc.pdp.core.condition.operators.Always;
import de.tum.in.i22.uc.pdp.core.condition.operators.Before;
import de.tum.in.i22.uc.pdp.core.condition.operators.ConditionParamMatchOperator;
import de.tum.in.i22.uc.pdp.core.condition.operators.During;
import de.tum.in.i22.uc.pdp.core.condition.operators.EvalOperator;
import de.tum.in.i22.uc.pdp.core.condition.operators.EventMatchOperator;
import de.tum.in.i22.uc.pdp.core.condition.operators.OSLAnd;
import de.tum.in.i22.uc.pdp.core.condition.operators.OSLFalse;
import de.tum.in.i22.uc.pdp.core.condition.operators.OSLImplies;
import de.tum.in.i22.uc.pdp.core.condition.operators.OSLNot;
import de.tum.in.i22.uc.pdp.core.condition.operators.OSLOr;
import de.tum.in.i22.uc.pdp.core.condition.operators.OSLTrue;
import de.tum.in.i22.uc.pdp.core.condition.operators.RepLim;
import de.tum.in.i22.uc.pdp.core.condition.operators.RepMax;
import de.tum.in.i22.uc.pdp.core.condition.operators.RepSince;
import de.tum.in.i22.uc.pdp.core.condition.operators.Since;
import de.tum.in.i22.uc.pdp.core.condition.operators.StateBasedOperator;
import de.tum.in.i22.uc.pdp.core.condition.operators.Within;


/**
 * <p>Java class for RepMaxType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RepMaxType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www22.in.tum.de/enforcementLanguage}Operators"/>
 *       &lt;/sequence>
 *       &lt;attribute name="limit" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RepMaxType", propOrder = {
    "operators"
})
public class RepMaxType
    extends Operator
{

    @XmlElements({
        @XmlElement(name = "true", type = OSLTrue.class),
        @XmlElement(name = "false", type = OSLFalse.class),
        @XmlElement(name = "not", type = OSLNot.class),
        @XmlElement(name = "or", type = OSLOr.class),
        @XmlElement(name = "and", type = OSLAnd.class),
        @XmlElement(name = "implies", type = OSLImplies.class),
        @XmlElement(name = "eventMatch", type = EventMatchOperator.class),
        @XmlElement(name = "conditionParamMatch", type = ConditionParamMatchOperator.class),
        @XmlElement(name = "since", type = Since.class),
        @XmlElement(name = "always", type = Always.class),
        @XmlElement(name = "before", type = Before.class),
        @XmlElement(name = "during", type = During.class),
        @XmlElement(name = "within", type = Within.class),
        @XmlElement(name = "repLim", type = RepLim.class),
        @XmlElement(name = "repSince", type = RepSince.class),
        @XmlElement(name = "repMax", type = RepMax.class),
        @XmlElement(name = "stateBasedFormula", type = StateBasedOperator.class),
        @XmlElement(name = "eval", type = EvalOperator.class)
    })
    protected Object operators;
    @XmlAttribute(name = "limit", required = true)
    protected long limit;

    /**
     * Gets the value of the operators property.
     * 
     * @return
     *     possible object is
     *     {@link TrueType }
     *     {@link FalseType }
     *     {@link NotType }
     *     {@link OrType }
     *     {@link AndType }
     *     {@link ImpliesType }
     *     {@link EventMatchingOperatorType }
     *     {@link ConditionParamMatchType }
     *     {@link SinceType }
     *     {@link AlwaysType }
     *     {@link BeforeType }
     *     {@link DuringType }
     *     {@link WithinType }
     *     {@link RepLimType }
     *     {@link RepSinceType }
     *     {@link RepMaxType }
     *     {@link StateBasedOperatorType }
     *     {@link EvalOperatorType }
     *     
     */
    public Object getOperators() {
        return operators;
    }

    /**
     * Sets the value of the operators property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueType }
     *     {@link FalseType }
     *     {@link NotType }
     *     {@link OrType }
     *     {@link AndType }
     *     {@link ImpliesType }
     *     {@link EventMatchingOperatorType }
     *     {@link ConditionParamMatchType }
     *     {@link SinceType }
     *     {@link AlwaysType }
     *     {@link BeforeType }
     *     {@link DuringType }
     *     {@link WithinType }
     *     {@link RepLimType }
     *     {@link RepSinceType }
     *     {@link RepMaxType }
     *     {@link StateBasedOperatorType }
     *     {@link EvalOperatorType }
     *     
     */
    public void setOperators(Object value) {
        this.operators = value;
    }

    public boolean isSetOperators() {
        return (this.operators!= null);
    }

    /**
     * Gets the value of the limit property.
     * 
     */
    public long getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     */
    public void setLimit(long value) {
        this.limit = value;
    }

    public boolean isSetLimit() {
        return true;
    }

}
