//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 01:48:04 PM CEST 
//

@ae.javax.xml.bind.annotation.XmlSchema(namespace = "http://www22.in.tum.de/time")
package de.tum.in.i22.uc.pdp.xsd.time;
